config/routes.rb
Rails.application.routes.draw do
  resources :trainers
  resources :tokimons
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tokimon.rb
class Tokimon < ApplicationRecord
  belongs_to :trainer

  validates(:name, presence: true)
  validates(:height, presence: true)
  validates(:weight, presence: true)
  validates(:fly, presence: true)
  validates(:fight, presence: true)
  validates(:fire, presence: true)
  validates(:water, presence: true)
  validates(:electric, presence: true)
  validates(:ice, presence: true)
  validates(:trainer_id, presence: true)

  def self.set_total(toki)
    toki.total = toki.fly + toki.fight + toki.fire + toki.water + toki.electric + toki.ice
    toki.save
  end

  def getAllAt(train)
    all_tokimons = Tokimon.where(:trainer_id => train.id)
    arr = Array.new()
    all_tokimons.each do |i|
      arr.push(i.name)
    end
    return arr
  end

end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :tokimons

  validates(:name, presence: true)
  validates(:level, presence: true)

  def self.set_level_default(train)
    train.level = 0
  end

  def self.update_level(train_id)
    trainer = Trainer.find(train_id)
    trainer.level = Tokimon.where(:trainer_id => train_id).length / 3
    trainer.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/tokimons_controller.rb
class TokimonsController < ApplicationController
  before_action :set_tokimon, only: [:show, :edit, :update, :destroy]

  # GET /tokimons
  # GET /tokimons.json
  def index
    @tokimons = Tokimon.all
  end

  # GET /tokimons/1
  # GET /tokimons/1.json
  def show
    @trainer = Trainer.find(@tokimon.trainer_id)
  end

  # GET /tokimons/new
  def new
    @tokimon = Tokimon.new
  end

  # GET /tokimons/1/edit
  def edit
  end

  # POST /tokimons
  # POST /tokimons.json
  def create
    @tokimon = Tokimon.new(tokimon_params)
    Tokimon.set_total(@tokimon)
    respond_to do |format|
      if @tokimon.save
        Trainer.update_level(@tokimon.trainer_id)

        format.html { redirect_to @tokimon, notice: 'Tokimon was successfully created.' }
        format.json { render :show, status: :created, location: @tokimon }
      else
        format.html { render :new }
        format.json { render json: @tokimon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokimons/1
  # PATCH/PUT /tokimons/1.json
  def update
    respond_to do |format|
      Tokimon.set_total(@tokimon)
      if @tokimon.update(tokimon_params)
        Tokimon.set_total(@tokimon)

        Trainer.update_level(@tokimon.trainer_id)

        format.html { redirect_to @tokimon, notice: 'Tokimon was successfully updated.' }
        format.json { render :show, status: :ok, location: @tokimon }
      else
        format.html { render :edit }
        format.json { render json: @tokimon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokimons/1
  # DELETE /tokimons/1.json
  def destroy
    @tokimon.destroy
    respond_to do |format|
      format.html { redirect_to tokimons_url, notice: 'Tokimon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tokimon
      @tokimon = Tokimon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tokimon_params
      params.require(:tokimon).permit(:name, :height, :weight, :fly, :fight, :fire, :water, :electric, :ice, :total, :trainer_id)
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers_tokimons = Tokimon.where(:trainer_id => @trainer_id)
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
    @trainers_tokimons = Tokimon.where(:trainer_id => @trainer_id)
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)
    Trainer.set_level_default(@trainer)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    trainers_tokimons = Tokimon.where(:trainer_id => @trainer.id)

    trainers_tokimons.each do |t|
      t.destroy
    end

    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:name, :level, :num_tokimon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tokimons_helper.rb
module TokimonsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar">
  <ul class="navlist">
    <li><a href="/tokimons">Tokimons</a></li>
    <li><a href="/trainers">Trainers</a></li>
    <li class="home"><a href="/" class="home">Tokidex</a></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tokidex!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="homebody">
  <h1 id="homeheader">
    Welcome to the Tokidex!
  </h1>

  <p>
    Use the navbar above to navigate the application! Start by clicking on either the Tokimons button or Trainers button! :)
  </p>

</div>

app/views/tokimons/_form.html.erb
<%= form_for(tokimon) do |f| %>
  <% if tokimon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tokimon.errors.count, "error") %> prohibited this tokimon from being saved:</h2>

      <ul>
      <% tokimon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div class="field">
    <%= f.label :fly %>
    <%= f.number_field :fly %>
  </div>

  <div class="field">
    <%= f.label :fight %>
    <%= f.number_field :fight %>
  </div>

  <div class="field">
    <%= f.label :fire %>
    <%= f.number_field :fire %>
  </div>

  <div class="field">
    <%= f.label :water %>
    <%= f.number_field :water %>
  </div>

  <div class="field">
    <%= f.label :electric %>
    <%= f.number_field :electric %>
  </div>

  <div class="field">
    <%= f.label :ice %>
    <%= f.number_field :ice %>
  </div>

  <div class="field">
    <%= f.label :trainer_id %>
    <%= f.collection_select :trainer_id, Trainer.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tokimons/edit.html.erb
<h1>Editing Tokimon</h1>

<%= render 'form', tokimon: @tokimon %>

<%= link_to 'Show', @tokimon %> |
<%= link_to 'Back', tokimons_path %>

app/views/tokimons/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="mainheader">Tokimons</h1>

<div class="erblink">
  <%= link_to 'New Tokimon', new_tokimon_path %>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>Weight</th>
      <th>Fly</th>
      <th>Fight</th>
      <th>Fire</th>
      <th>Water</th>
      <th>Electric</th>
      <th>Ice</th>
      <th>Total</th>
      <th>Trainer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokimons.each do |tokimon| %>
      <tr>
        <td><%= tokimon.name %></td>
        <td><%= tokimon.height %></td>
        <td><%= tokimon.weight %></td>
        <td><%= tokimon.fly %></td>
        <td><%= tokimon.fight %></td>
        <td><%= tokimon.fire %></td>
        <td><%= tokimon.water %></td>
        <td><%= tokimon.electric %></td>
        <td><%= tokimon.ice %></td>
        <td><%= tokimon.total %></td>
        <td><%= tokimon.trainer_id%></td>
        <td><%= link_to 'Show', tokimon %></td>
        <td><%= link_to 'Edit', edit_tokimon_path(tokimon) %></td>
        <td><%= link_to 'Destroy', tokimon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tokimons/new.html.erb
<h1>New Tokimon</h1>

<%= render 'form', tokimon: @tokimon %>

<%= link_to 'Back', tokimons_path %>

app/views/tokimons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Name:
  <%= @tokimon.name %>
</p>

<p>
  Height:
  <%= @tokimon.height %>
</p>

<p>
  Weight:
  <%= @tokimon.weight %>
</p>

<p>
  Fly:
  <%= @tokimon.fly %>
</p>

<p>
  Fight:
  <%= @tokimon.fight %>
</p>

<p>
  Fire:
  <%= @tokimon.fire %>
</p>

<p>
  Water:
  <%= @tokimon.water %>
</p>

<p>
  Electric:
  <%= @tokimon.electric %>
</p>

<p>
  Ice:
  <%= @tokimon.ice %>
</p>

<p>
  Total:
  <%= @tokimon.total %>
</p>

<p>
  Trainer:
  <%= @trainer.name %>
  <%= link_to 'Show', @trainer %>
  <%= link_to 'Edit', edit_trainer_path(@trainer) %>
</p>

<%= link_to 'Edit', edit_tokimon_path(@tokimon) %> |
<%= link_to 'Back', tokimons_path %>

app/views/trainers/_form.html.erb
<%= form_for(trainer) do |f| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainers</h1>

<div class="erblink">
  <%= link_to 'New Trainer', new_trainer_path %>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainers.each do |trainer| %>
      <tr>
        <td><%= trainer.name %></td>
        <td><%= trainer.level %></td>
        <td>
          <%= Tokimon.getAllAt(trainer).each do |t| %>
          <% end %>

        </td>
        <td><%= link_to 'Show', trainer %></td>
        <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
        <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure? You\'ll be deleting all tokimon associated with this trainer.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainer Profile</h1>

<p>
  Name:
  <%= @trainer.name %>
</p>

<p>
  Level:
  <%= @trainer.level %>
</p>

<p>
  Tokimons:
  <%= @trainers_tokimons.each do |t| %>
  <%= t.name %>
  <% end %>

</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>